### ISSUE TITLE
getRolePath(name) and getAgentPath(name) does not handle ambiguous search result

### ISSUE THREAD

**Issue by kovax** [cristal-ise/lookup-ldap#2]
When there are to RolePath in the system '/domain/agent/User/Dummy' and '/domain/agent/Admin/Dummy'

getRolePath("Dummy") is based on searching the LDAP tree, which means the search find 2 entries but the system will gracefully return the first one. I suggest to throw a new exception in case of ambiguous search result

**Comment by abranson** [comment]
The kernel should enforce unique agent and role names, as they are referenced without path or id in activities and descriptions. I'll fix this there.
